from youtube_transcript_api import YouTubeTranscriptApi
from youtube_transcript_api.formatters import JSONFormatter
# retrieve the available transcripts
transcript_list = YouTubeTranscriptApi.list_transcripts('F8f_Tobdu6o') # input 형식으로 받기      UFTkjxSeDIc     F8f_Tobdu6o
formatter = JSONFormatter()
# iterate over all available transcripts
for transcript in transcript_list:

    # # the Transcript object provides metadata properties
    print(
        # transcript.video_id,
        transcript.language,
        transcript.language_code,
        # whether it has been manually created or generated by YouTube
        # transcript.is_generated,
        # whether this transcript can be translated or not
        # transcript.is_translatable,
        # a list of languages the transcript can be translated to
        # transcript.translation_languages,
    )
    a = transcript.fetch()
    b = ''
    # fetch the actual transcript data
    if transcript.language_code == 'ko':
        for i in range(len(a)):
            b += a[i]['text']
            b += ' '
    print(b)
    file = open("text.txt", "w") 
    file.write(b)
    file.close()
    # print(a)

    # translating the transcript will return another transcript object
    # print(transcript.translate('en').fetch())

# you can also directly filter for the language you are looking for, using the transcript list
# transcript = transcript_list.find_transcript(['ko'])  

# or just filter for manually created transcripts  
# transcript = transcript_list.find_manually_created_transcript(['ko'])  

# or automatically generated ones  
# transcript = transcript_list.find_generated_transcript(['ko'])


# json_formatted = formatter.format_transcript(transcript)
# with open('your_filename.json', 'w', encoding='utf-8') as json_file:
#     json_file.write(json_formatted)
    

